name: Lint

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - '.pylintrc'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - '.pylintrc'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8, 3.9 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up poetry
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install --no-root
      - name: Lint with pylint and black
        run: |
          poetry run ./scripts/run_pylint.sh
          poetry run ./scripts/run_black.sh
