name: Ruff

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - '.pylintrc'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/ruff-action@v2
